Repository ohcnetwork/care, pull requests merged in 2020-03, with the labels that each got.

#109 Updates: Don't override creator
  care/facility/api/mixins.py
  care/facility/api/viewsets/__init__.py
  care/facility/api/viewsets/facility.py
  care/facility/api/viewsets/patient.py
  care/facility/tests/test_facility.py
Labels: ready-to-merge

#123 Change variable name for the choice of type in LocalBodyModel
  care/facility/migrations/0028_auto_20200326_1752.py
  care/facility/migrations/0030_merge_20200326_2047.py
  care/users/migrations/0012_auto_20200326_1752.py
  care/users/migrations/0013_auto_20200326_2021.py
  care/users/models.py
Labels: ready-to-merge

#105 Feat/add state district panchayath apis
  care/facility/api/serializers/ambulance.py
  care/facility/api/serializers/facility.py
  care/facility/api/viewsets/ambulance.py
  care/facility/api/viewsets/facility.py
  care/facility/migrations/0026_map_to_district.py
  care/facility/migrations/0030_auto_20200327_0619.py
  care/facility/migrations/0031_rename_kasargode.py
  care/facility/migrations/0032_merge_20200327_1215.py
  care/facility/models/facility.py
  care/facility/tests/test_facility.py
  care/facility/tests/test_patient.py
  care/users/admin.py
  care/users/api/__init__.py
  care/users/api/serializers/__init__.py
  care/users/api/serializers/lsg.py
  care/users/api/serializers/user.py
  care/users/api/viewsets/__init__.py
  care/users/api/viewsets/lsg.py
  care/users/api/viewsets/users.py
  care/users/management/__init__.py
  care/users/management/commands/__init__.py
  care/users/management/commands/load_lsg_data.py
  care/users/migrations/0011_map_users_to_district.py
  care/users/migrations/0012_auto_20200326_0342.py
  care/users/migrations/0013_auto_20200327_0437.py
  care/users/migrations/0014_restart_sequence_districts.py
  care/users/migrations/0015_merge_20200327_1215.py
  care/users/models.py
  care/users/tests/test_users.py
  config/api_router.py
  config/tests/fixtures.py
  config/tests/helper.py
  conftest.py
  pytest.ini
Labels: waiting-for-review

#138 add district admin level access
  care/facility/api/mixins.py
  care/users/migrations/0016_auto_20200327_1954.py
  care/users/models.py
Labels: blocked, waiting-for-review

#136 add history to capacity
  care/facility/api/serializers/facility_capacity.py
  care/facility/api/viewsets/facility_capacity.py
  care/facility/migrations/0035_historicalfacilitycapacity.py
  care/facility/models/facility.py
  config/settings/base.py
  requirements/base.txt
  setup.cfg
Labels: waiting-for-review
