Repository ohcnetwork/care, pull requests merged in 2022-12, with the labels that each got.

#1109 feat(file_upload): added new fields in file model and fixed file update permission
  care/facility/api/serializers/file_upload.py
  care/facility/migrations/0327_fileupload_archived_by.py
  care/facility/models/file_upload.py
Labels: waiting-for-review, P1

#1114 Refactor home_facility to home_facility_obj
  care/users/api/serializers/user.py
Labels: waiting-for-review

#1121 Added validation for 11 digit toll free numbers
  care/facility/models/asset.py
  care/users/models.py
Labels: waiting-for-review, P1

#1122 Added delete endpoint for assets
  care/facility/api/viewsets/asset.py
Labels: waiting-for-review

#1127 Used facility.middleware_address for asset.meta.middleware_hostname in AssetIntgration
  care/facility/api/viewsets/asset.py
Labels: P1

#1112 feat(file_upload): added a filter to filter out the archive file
  care/facility/api/viewsets/file_upload.py
Labels: waiting-for-review
