Repository ohcnetwork/care, pull requests merged in 2022-11, with the labels that each got.

#1094 fix(report): correction of logo present in the patient discharge summary
  care/templates/reports/patient_pdf_report.html
Labels: waiting-for-review, P1

#1091 Add endpoint to check the validity of a password reset token
  care/users/reset_password_views.py
  config/ratelimit.py
  config/urls.py
Labels: waiting-for-review, done

#1097 check_availability api will also consider deleted users
  care/users/api/viewsets/users.py
  care/users/models.py
Labels: waiting-for-review, done

#1090 feat: Added admitted bed type filter
  care/facility/api/viewsets/patient.py
Labels: waiting-for-review, done, P1
