Repository ohcnetwork/care, pull requests merged in 2022-09, with the labels that each got.

#1006 Deprecates text field `warranty_details` of Asset
  care/facility/models/asset.py
Labels: Clean Up

#1013 delete cached asset object only on update
  care/facility/api/serializers/asset.py
Labels: P1

#1007 Deprecate Covid Category and adds Patient Category in Daily Rounds and Consultation
  care/facility/api/serializers/daily_round.py
  care/facility/api/serializers/patient_consultation.py
  care/facility/api/viewsets/patient.py
  care/facility/migrations/0315_auto_20220908_1027.py
  care/facility/migrations/0316_auto_20220908_1112.py
  care/facility/models/daily_round.py
  care/facility/models/patient.py
  care/facility/models/patient_base.py
  care/facility/models/patient_consultation.py
  care/facility/reports/admin_reports.py
  care/utils/tests/test_base.py
Labels: ready-to-merge

#1016 modify pressure_sore and create new pain_scale_enhanced field
  care/facility/migrations/0315_auto_20220909_0925.py
  care/facility/models/daily_round.py
  care/facility/models/json_schema/daily_round.py
Labels: reviewed

#1037 Implements management command `load_dummy_data`
  care/facility/management/commands/load_dummy_data.py
  data/dummy/facility.json
  data/dummy/users.json
Labels: done

#1039 Adds `load_dummy_data` management command in docs.
  docs/django-commands/configuration.rst
Labels: documentation, done
