Repository ohcnetwork/care, pull requests merged in 2022-07, with the labels that each got.

#874 Added features for facilities
  care/facility/api/serializers/facility.py
  care/facility/migrations/0298_facility_features.py
  care/facility/models/facility.py
Labels: reviewed

#906 updated message when token is not valid
  config/authentication.py
Labels: peer-reviewed

#736 Prevent creation of bed with the same name
  care/facility/api/viewsets/bed.py
  care/facility/models/bed.py
Labels: reviewed

#821 Add a "working" filter for Assets
  care/facility/api/serializers/asset.py
  care/facility/api/viewsets/asset.py
  care/facility/models/asset.py
Labels: waiting-for-review

#892 Fixed Log update error
  care/facility/api/serializers/daily_round.py
Labels: reviewed

#854 update patient bed switching logic
  care/facility/api/serializers/bed.py
Labels: reviewed

#902 Added discharge_reason and discharge_notes in Patient Consultation
  care/facility/api/serializers/patient_consultation.py
  care/facility/api/viewsets/patient.py
  care/facility/migrations/0301_auto_20220709_2051.py
  care/facility/models/patient_base.py
  care/facility/models/patient_consultation.py
Labels: P1

#931 Fixed malfunction in facility creation
  care/facility/models/mixins/permissions/facility.py
Labels: P1
