Repository ohcnetwork/care, pull requests merged in 2022-10, with the labels that each got.

#1055 Adds `archive_reason` to `FileUpload` and validate if `is_archived`
  care/facility/api/serializers/file_upload.py
  care/facility/migrations/0323_fileupload_archive_reason.py
  care/facility/models/file_upload.py
Labels: done

#1042 Store review_interval and use it to compute next review_time
  care/facility/api/serializers/daily_round.py
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0322_patientconsultation_review_interval.py
  care/facility/models/patient_consultation.py
Labels: waiting-for-review

#1043 Added API View to check availability of username
  care/users/api/viewsets/users.py
  config/api_router.py
Labels: ready-to-merge

#1072 fix issues in #1043, username availability endpoint: `/users/{username}/check_availability/`
  care/users/api/viewsets/users.py
  config/api_router.py
Labels: waiting-for-review, done, P1
