Repository ohcnetwork/care, pull requests merged in 2022-06, with the labels that each got.

#828 update coverage-package and config
  .coveragerc
  care/facility/migrations/0101_populate_countries_travelled.py
  config/settings/test.py
  requirements/local.txt
  setup.cfg
Labels: Tests

#824 updated user tests, removed facility tests
  care/facility/tests/test_facility_api.py
  care/facility/tests/test_facility_patient_history_api.py
  care/facility/tests/test_migrations.py
  care/facility/tests/test_patient_api.py
  care/facility/tests/test_patient_consultation_api.py
  care/facility/tests/test_patient_daily_rounds_api.py
  care/facility/tests/test_patient_sample_api.py
  care/users/api/viewsets/users.py
  care/users/models.py
  care/users/tests/test_api.py
  care/users/tests/test_facility_user_create.py
  care/utils/tests/test_base.py
  config/settings/test.py
  manage.py
Labels: Tests, changes required

#826 add workflow to build and deploy docs
  .github/workflows/deployment.yaml
  .github/workflows/docs.yml
  docs/_static/.gitkeep
  docs/conf.py
  requirements/docs.txt
  requirements/local.txt
Labels: documentation

#814 Endpoint analyse/ fixed for read-only users
  .gitignore
  care/facility/models/daily_round.py
Labels: waiting-for-review

#871 /test_sample route fixed for staff readonly
  care/facility/models/patient_sample.py
Labels: waiting-for-review
