Repository ohcnetwork/care, pull requests merged in 2023-01, with the labels that each got.

#1155 fix: Add new fields for patient discharge feature
  care/facility/api/viewsets/patient.py
  care/facility/migrations/0333_auto_20230112_2233.py
  care/facility/models/patient_consultation.py
Labels: P1

#1143 Feat: Add a consultation_status field in consultation model
  care/facility/migrations/0332_patientconsultation_consultation_status.py
  care/facility/migrations/0334_merge_20230113_1507.py
  care/facility/models/patient_base.py
  care/facility/models/patient_consultation.py
Labels: P1

#1158 Add asset class to Asset filters
  care/facility/api/viewsets/asset.py
Labels: waiting-for-review

#1151 Adds doctor specialisation related fields to User Model
  care/users/api/serializers/user.py
  care/users/migrations/0045_auto_20230110_1120.py
  care/users/models.py
Labels: waiting-for-review

#789 Fix inconsistent type of visited countries attribute
  care/facility/api/serializers/patient_icmr.py
  care/facility/api/serializers/patient_sample.py
Labels: reviewed

#1165 fix: Error during creating new asset
  care/facility/api/serializers/asset.py
Labels: waiting-for-review, done, P1
