Repository ohcnetwork/care, pull requests merged in 2023-07, with the labels that each got.

#1418 hotfix: pin to pydantic v1 for fhir.resources
  requirements/base.txt
Labels: waiting-for-review, P1

#1416 Remove PII from Patient CSV export
  care/facility/models/patient.py
Labels: waiting-for-review, P1

#1420 fix prescribed_medication variable in patient discharge summary
  care/templates/reports/patient_pdf_report.html
Labels: waiting-for-review, P1

#1415 Adds validation to consulation date fields (`admission_date`, `discharge_date`, `death_datetime`)
  .vscode/launch.json
  care/facility/api/serializers/patient_consultation.py
  care/facility/tests/test_patient_consultation_api.py
  care/users/tests/test_api.py
  care/utils/tests/test_base.py
Labels: waiting-for-review, P1

#1428 Adds migration to move `ip_no` to `op_no` for non admission consultations
  care/facility/migrations/0367_auto_20230704_1646.py
  care/facility/migrations/0370_merge_20230705_1500.py
Labels: waiting-for-review

#1431 fix: adds tests for auth and token endpoints
  care/users/tests/test_auth.py
  care/utils/tests/test_base.py
Labels: reviewed

#1436 Revert "Load medicines to in-memory on django start (#1432)"
  config/wsgi.py
Labels: waiting-for-review

#1440 Add discharge_reason filter for patient
  care/facility/api/viewsets/patient.py
Labels: reviewed

#1437 add silk profiler
  config/settings/local.py
  config/urls.py
  requirements/local.txt
Labels: reviewed

#1441 Add `home_facility` to `UserBaseMinimumSerializer`
  care/facility/tests/test_patient_api.py
  care/users/api/serializers/user.py
  care/utils/tests/test_base.py
Labels: reviewed

#1443 Medibase: Drop littletable; instead store as list from ORM's `values_list`
  care/facility/api/viewsets/prescription.py
  care/facility/static_data/medibase.py
  config/wsgi.py
Labels: P1

#1448 Adds `chapter`, `root_block`, `root_category` columns to `meta_icd11_diagnosis` DB table
  care/facility/management/commands/load_meta_icd11_diagnosis.py
  care/facility/migrations/0371_metaicd11diagnosis_chapter_and_more.py
  care/facility/models/meta_icd11_diagnosis.py
Labels: waiting-for-review

#1449 Update branding from CoronaSafe Network to Open Healthcare Network
  care/facility/api/serializers/patient_otp.py
  care/templates/base.html
  care/templates/email/user_reset_password.html
  care/templates/email/user_reset_password.txt
Labels: waiting-for-review

#1452 Fixes string representation of `MedibaseMedicine` model
  care/facility/models/prescription.py
Labels: waiting-for-review, P1

#1454 Asset Tracking and Monitoring Enhancements
  care/facility/api/serializers/asset.py
  care/facility/api/viewsets/asset.py
  care/facility/migrations/0372_assetavailabilityrecord.py
  care/facility/models/asset.py
  care/facility/tasks/__init__.py
  care/facility/tasks/asset_monitor.py
  care/facility/tests/test_asset_api.py
  care/facility/tests/test_asset_availability_api.py
  care/facility/tests/test_medibase_api.py
  care/facility/tests/test_patient_daily_rounds_api.py
  care/users/tests/test_facility_user_create.py
  care/utils/assetintegration/base.py
  config/api_router.py
Labels: waiting-for-review

#1466 Mark asset as down when middleware is down
  care/facility/tasks/asset_monitor.py
Labels: waiting-for-review, P1

#1464 add patient_category ShiftingSerializer
  care/facility/api/serializers/shifting.py
Labels: reviewed

#1461 return proper data type from symptomatic_international_traveller
  care/facility/models/patient_icmr.py
Labels: reviewed

#1459 don't summarize deleted facilities
  care/facility/utils/summarisation/facility_capacity.py
Labels: reviewed

#1309 remove unused hba1c field from patient consultation
  care/facility/migrations/0373_remove_patientconsultation_hba1c.py
  care/facility/models/patient_consultation.py
  data/dummy/facility.json
Labels: reviewed

#1445 add created_by_local_user_content field for patients notes
  care/facility/api/serializers/patient.py
  care/facility/api/viewsets/patient.py
  care/facility/tests/test_patient_api.py
  care/users/api/serializers/user.py
Labels: reviewed

#1430 added referred_to_external field PatientConsultationDischargeSerializer
  care/facility/api/serializers/patient_consultation.py
  care/facility/tests/test_patient_consultation_api.py
Labels: reviewed

#1471 Pop "patient_category" in local `validated_data` instead of `self.validated_data`
  care/facility/api/serializers/shifting.py
Labels: waiting-for-review, P1

#1468 Adds `REDIS_URL` to `.local.env`
  docker/.local.env
Labels: reviewed

#1475 Ignore admission date during discharge process if not provided
  care/facility/api/serializers/patient_consultation.py
Labels: P1

#1481 Shifting: Skip changing `last_consultation.category` if `patient_category` is not present in `validated_data`
  care/facility/api/serializers/shifting.py
Labels: waiting-for-review, P1

#1476 Set Minimum Value to 0 for Respiratory Rate Field in DailyRound Model
  care/facility/models/daily_round.py
Labels: P1, reviewed

#1487 Add monitoring for Cameras
  care/facility/tasks/asset_monitor.py
Labels: In progress
