Repository ohcnetwork/care, pull requests merged in 2023-02, with the labels that each got.

#1173 fixed fetching user skills
  care/users/api/viewsets/userskill.py
Labels: P1

#1174 Update Patient CSV Export
  care/facility/models/patient.py
  care/facility/models/patient_consultation.py
Labels: waiting-for-review

#1175 Fix symptomatic_international_traveller crash
  care/facility/models/patient_icmr.py
Labels: waiting-for-review

#1163 Refactor Symptoms
  care/facility/models/patient_base.py
Labels: ops-review-pending

#1181 Migration for new Symptoms
  care/facility/migrations/0335_auto_20230207_1914.py
Labels: P1

#1183 Update datetime format to `DD/MM/YYYY HH:mm` for Patient CSV Export
  care/facility/models/patient.py
Labels: waiting-for-review, done

#1188 Adds `skills` to `UserAssignedSerializer`
  care/users/api/serializers/user.py
Labels: waiting-for-review, done

#1197 Purge Deprecated Admin Reports
  care/facility/management/commands/generate_district_admin_summary.py
  care/facility/management/commands/generate_state_admin_summary.py
  care/facility/reports/admin_reports.py
  care/utils/notification_handler.py
  care/utils/whatsapp/send_media_message.py
  care/utils/whatsapp/send_mesage.py
Labels: waiting-for-review

#1194 Add endpoint to clear user's home facility
  care/users/api/viewsets/users.py
Labels: waiting-for-review

#1198 Only allow >=DistrictAdmin to clear home facility
  care/users/api/viewsets/users.py
Labels: waiting-for-review

#1196 Allow skills access for any user
  care/users/api/viewsets/userskill.py
Labels: waiting-for-review
