Repository ohcnetwork/care, pull requests merged in 2023-03, with the labels that each got.

#1212 Clone specific fields for 'Normal' type daily rounds
  care/facility/api/serializers/daily_round.py
Labels: waiting-for-review, P1

#1216 Add facility name, patient name and bed name to Patient's ordering_fields
  care/facility/api/viewsets/patient.py
Labels: waiting-for-review, P1

#1218 fix: Add more fields in the patient export CSV
  care/facility/models/patient.py
Labels: waiting-for-review, P1

#1215 Update Review Interval in Patient Consultation for Daily Round Entries
  care/facility/api/serializers/daily_round.py
Labels: waiting-for-review, P2

#1225 Disables API docs in production
  config/urls.py
Labels: done

#1226 fixes patient age filter
  care/facility/api/viewsets/patient.py
Labels: done, P1
