Repository ohcnetwork/care, pull requests merged in 2023-09, with the labels that each got.

#1570 Medicine Administrations: Add validations to `administered_date`
  care/facility/api/serializers/prescription.py
  care/facility/api/viewsets/prescription.py
  care/facility/tests/test_medicine_administrations_api.py
Labels: waiting-for-review

#1533 added bed_id to reponse of patient_from_asset
  care/facility/api/serializers/patient_consultation.py
Labels: reviewed

#1565 Reject Prescription Creation if Medicine already Prescribed and is active
  care/facility/api/serializers/prescription.py
  care/facility/api/viewsets/prescription.py
  care/facility/tests/test_prescriptions_api.py
Labels: reviewed

#1573 Adds field for Principal Diagnosis
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0383_patientconsultation_icd11_principal_diagnosis.py
  care/facility/models/patient_consultation.py
  care/facility/utils/reports/discharge_summary.py
  care/templates/reports/patient_discharge_summary_pdf.html
Labels: waiting-for-review

#1569 temporarily expose abdm health facility apis directly
  care/abdm/api/serializers/health_facility.py
  care/abdm/api/viewsets/health_facility.py
  care/abdm/migrations/0010_healthfacility_registered.py
  care/abdm/models.py
  care/abdm/permissions.py
  config/api_router.py
Labels: reviewed

#1582 Fix Swagger
  care/facility/api/serializers/patient_consultation.py
Labels: reviewed

#1567 Foreign Key to User for Consultation Verified By
  care/abdm/utils/fhir.py
  care/facility/api/serializers/patient_consultation.py
  care/facility/api/viewsets/facility_users.py
  care/facility/migrations/0384_patientconsultation_verified_by.py
  care/facility/models/patient_consultation.py
  care/facility/tests/test_patient_consultation_api.py
  care/templates/reports/patient_discharge_summary_pdf.html
  care/users/api/viewsets/users.py
  data/dummy/facility.json
Labels: waiting-for-review

#1586 PatientConsultation: Skip `verified_by` required validation if `suggestion` is DD
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0385_alter_patientconsultation_verified_by.py
  care/facility/models/patient_consultation.py
  care/facility/tests/test_patient_consultation_api.py
Labels: waiting-for-review, P1

#1318 Added a way to handle filtering admitted but no bed assigned
  care/facility/api/viewsets/patient.py
  care/facility/tests/test_patientfilterset.py
Labels: reviewed

#1592 CSV export for Assets
  care/facility/api/serializers/asset.py
  care/facility/api/viewsets/asset.py
  care/facility/models/asset.py
Labels: waiting-for-review, P1

#1572 add field readmission + custom migration
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0385_patientconsultation_is_readmission.py
  care/facility/models/patient_consultation.py
Labels: reviewed

#1583 Adds `deleted` and `chapter_short` fields to Meta ICD11 Table
  care/facility/management/commands/load_meta_icd11_diagnosis.py
  care/facility/migrations/0384_metaicd11diagnosis_chapter_short_and_more.py
  care/facility/models/meta_icd11_diagnosis.py
Labels: reviewed

#1595 Delete duplicate `AssetBed` records of "HL7MONITOR" `asset_class`
  care/facility/migrations/0386_auto_20230911_1726.py
Labels: waiting-for-review

#1623 rename verified by to treating physician in discharge summary
  care/templates/reports/patient_discharge_summary_pdf.html
Labels: waiting-for-review

#1608 Adds `discontinued` filter for prescriptions viewset
  care/facility/api/viewsets/prescription.py
Labels: waiting-for-review

#1643 Prescription: fixes `last_administered_on`
  care/facility/api/serializers/prescription.py
Labels: waiting-for-review
