Repository ohcnetwork/care, pull requests merged in 2023-11, with the labels that each got.

#1700 Fixes N+1 queries in Daily Rounds
  care/facility/api/viewsets/daily_round.py
Labels: waiting-for-review

#1690 Adds M2M Consultation Diagnosis model
  care/abdm/utils/fhir.py
  care/facility/api/serializers/consultation_diagnosis.py
  care/facility/api/serializers/patient_consultation.py
  care/facility/api/viewsets/consultation_diagnosis.py
  care/facility/api/viewsets/icd.py
  care/facility/api/viewsets/patient.py
  care/facility/management/commands/load_icd11_diagnoses_data.py
  care/facility/migrations/0001_initial_squashed.py
  care/facility/migrations/0393_rename_diagnosis_patientconsultation_deprecated_diagnosis_and_more.py
  care/facility/migrations_old/0353_auto_20230429_2026.py
  care/facility/models/icd11_diagnosis.py
  care/facility/models/mixins/permissions/patient.py
  care/facility/models/patient.py
  care/facility/models/patient_consultation.py
  care/facility/static_data/icd11.py
  care/facility/tests/test_patient_consultation_api.py
  care/facility/utils/reports/discharge_summary.py
  care/hcx/api/viewsets/gateway.py
  care/templates/reports/patient_discharge_summary_pdf.html
  config/api_router.py
Labels: waiting-for-review, P2

#1712 Fix for Incorrect Discharge Reasons in Patient Transfers and Readmissions
  care/facility/api/serializers/patient.py
  care/facility/api/viewsets/patient.py
  care/facility/migrations/0394_auto_20231114_2219.py
  care/facility/tests/test_patient_api.py
  care/utils/tests/test_utils.py
Labels: P1

#1678 Patient Consultation: Route to Facility 🏥, Admission Date & Time 🕚, Rename variable: `verified_by` to `treating_physician`
  care/abdm/utils/fhir.py
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0394_rename_consultation_status_patientconsultation_route_to_facility_and_more.py
  care/facility/migrations/0395_alter_patientconsultation_route_to_facility.py
  care/facility/models/patient.py
  care/facility/models/patient_base.py
  care/facility/models/patient_consultation.py
  care/facility/tests/test_patient_consultation_api.py
  care/templates/reports/patient_discharge_summary_pdf.html
  data/dummy/facility.json
Labels: waiting-for-review

#1724 fix migrations
  care/facility/migrations/0396_merge_20231122_0240.py
Labels: P1

#1733 Fix edge case for middleware hostname override in asset.py
  care/facility/api/viewsets/asset.py
  care/facility/tasks/asset_monitor.py
Labels: waiting-for-review, P1
