Repository ohcnetwork/care, pull requests merged in 2023-05, with the labels that each got.

#1289 bump `isort` as pre-commit initialize fails with older version
  .pre-commit-config.yaml
  requirements/local.txt
Labels: waiting-for-review

#1247 Refactor discharge summary endpoints and Converted prescription field to their own models, views and serializers
  .pre-commit-config.yaml
  care/facility/api/serializers/patient_consultation.py
  care/facility/api/serializers/prescription.py
  care/facility/api/serializers/prescription_supplier.py
  care/facility/api/viewsets/patient.py
  care/facility/api/viewsets/patient_consultation.py
  care/facility/api/viewsets/prescription.py
  care/facility/migrations/0353_auto_20230429_2026.py
  care/facility/migrations/0354_auto_20230429_2027.py
  care/facility/migrations/0355_auto_20230512_1122.py
  care/facility/models/__init__.py
  care/facility/models/file_upload.py
  care/facility/models/patient_consultation.py
  care/facility/models/prescription.py
  care/facility/static_data/icd11.py
  care/facility/tasks/patient/discharge_report.py
  care/facility/templatetags/filters.py
  care/templates/reports/patient_pdf_report.html
  config/api_router.py
Labels: waiting-for-review, P2

#1305 fix prescriptions migration
  care/facility/migrations/0354_auto_20230519_1501.py
  care/facility/migrations/0355_auto_20230429_2027.py
  care/facility/migrations/0356_auto_20230512_1122.py
  care/facility/migrations/0357_auto_20230523_1304.py
  care/facility/models/prescription.py
Labels: waiting-for-review

#1314 Create `ConsultationBed` only on if Admission and migrates existing non-admission `ConsultationBed`s.
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0358_auto_20230524_1853.py
Labels: waiting-for-review, P1

#1312 Adds a check on `is_occupied` for bed delete action
  care/facility/api/viewsets/bed.py
Labels: waiting-for-review, P1

#1302 Adds API for `PatientAssetBed`
  care/facility/api/serializers/bed.py
  care/facility/api/viewsets/bed.py
  config/api_router.py
Labels: waiting-for-review

#1315 bug fix: make discharge notes optional; discharge date required
  care/facility/api/serializers/patient_consultation.py
Labels: waiting-for-review, P1

#1316 Discharge Notes: Allow Blank
  care/facility/api/serializers/patient_consultation.py
Labels: waiting-for-review, P1
