Repository ohcnetwork/care, pull requests merged in 2023-12, with the labels that each got.

#1726 Support filtering daily rounds by `taken_at` range
  care/facility/api/viewsets/daily_round.py
Labels: waiting-for-review, P2

#1750 Refactor asset status check logic
  care/facility/tasks/asset_monitor.py
Labels: waiting-for-review, P1

#1738 Allow district admin to delete users
  care/users/api/viewsets/users.py
Labels: waiting-for-review

#1736 show icu admission date in discharge summary pdf
  care/templates/reports/patient_discharge_summary_pdf.html
Labels: waiting-for-review

#1708 Field to classify location as an ICU or Ward or Other
  care/facility/api/serializers/asset.py
  care/facility/migrations/0394_alter_assetlocation_location_type.py
  care/facility/models/asset.py
  care/facility/tests/test_asset_location_api.py
Labels: reviewed

#1747 Check if user uploading External results is from same district
  care/facility/api/viewsets/patient_external_test.py
Labels: waiting-for-review

#1748 Add More Facilities and patients to dummy data
  data/dummy/facility.json
Labels: waiting-for-review, P2

#1741 Add `resolved_middleware` JSON field to Asset Serializer.
  care/facility/api/serializers/asset.py
  care/facility/models/asset.py
Labels: waiting-for-review

#1157 Restrict Admin from unlinking users from other district
  care/facility/tests/test_unlink_district_admins.py
  care/users/api/viewsets/users.py
Labels: waiting-for-review

#1762 fix: Import External Result is failing for valid data
  care/facility/api/viewsets/patient_external_test.py
  care/facility/tests/test_upload_external_result.py
  care/utils/tests/test_utils.py
Labels: P1

#1760 Add Telemedicine as a rounds type option
  care/facility/api/serializers/daily_round.py
  care/facility/migrations/0403_alter_dailyround_rounds_type.py
  care/facility/models/daily_round.py
Labels: waiting-for-review

#1728 Rename `admission_date` to `encounter_date` and clean column
  care/abdm/utils/fhir.py
  care/facility/api/serializers/bed.py
  care/facility/api/serializers/patient_consultation.py
  care/facility/api/viewsets/patient.py
  care/facility/migrations/0403_rename_admission_date_to_encounter_date_and_more.py
  care/facility/models/patient_consultation.py
  care/facility/models/patient_icmr.py
  care/facility/tests/test_consultation_bed_api.py
  care/facility/tests/test_patient_api.py
  care/facility/tests/test_patient_consultation_api.py
  care/templates/reports/patient_discharge_summary_pdf.html
  care/utils/tests/test_utils.py
  data/dummy/facility.json
Labels: waiting-for-review, P2

#1793 Updated the bridge service registration endpoint
  aws/backend.json
  aws/celery.json
  care/abdm/api/viewsets/health_facility.py
  care/abdm/utils/api_call.py
  config/settings/base.py
Labels: bug, P1, reviewed, ABDM
