Repository ohcnetwork/care, pull requests merged in 2023-04, with the labels that each got.

#1233 Update patient category choices wording (Abnormal instead of Slightly Abnormal )
  care/facility/models/patient_base.py
Labels: waiting-for-review

#1232 fix: added op_no field and respiratory support filter
  care/facility/api/viewsets/patient.py
  care/facility/migrations/0336_patientconsultation_op_no.py
  care/facility/models/patient_consultation.py
Labels: waiting-for-review

#1235 Add patient ordering by category
  care/facility/api/viewsets/patient.py
Labels: waiting-for-review, P2

#1228 Add referred_to_external to PatientConsultation
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0337_patientconsultation_referred_to_external.py
  care/facility/migrations/0338_auto_20230323_1249.py
  care/facility/models/patient_consultation.py
  care/hcx/migrations/0006_auto_20230323_1208.py
Labels: waiting-for-review

#1238 Added enum value for oxygen support in critical care
  care/facility/migrations/0341_auto_20230407_0346.py
  care/facility/models/daily_round.py
Labels: waiting-for-review, P1

#1239 Add fields to store discharge prescription
  care/facility/api/serializers/patient_consultation.py
  care/facility/api/viewsets/patient.py
  care/facility/migrations/0342_auto_20230407_1424.py
  care/facility/models/patient_consultation.py
Labels: waiting-for-review, P1

#1240 Make Discharge prescription fields optional
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0343_auto_20230407_1850.py
  care/facility/models/patient_consultation.py
Labels: waiting-for-review

#1245 Fixes Patient Category Filter
  care/facility/api/viewsets/patient.py
Labels: waiting-for-review

#1249 Reorders and Adds Policy to Patient Export
  care/facility/models/patient.py
Labels: waiting-for-review, P1

#1250 Fix incorrect discharge date for patients
  care/facility/api/viewsets/patient.py
Labels: waiting-for-review

#1251 Filter skills by `userskill__deleted=False` in `UserAssignedSerializer`
  care/users/api/serializers/user.py
Labels: waiting-for-review, P1

#1231 Add unique constraint for AssetLocation name and facility
  care/facility/api/serializers/asset.py
  care/facility/api/viewsets/asset.py
Labels: waiting-for-review

#1257 Removed whatsapp refs introduced with hcx pr
  care/utils/notification_handler.py
Labels: waiting-for-review

#1234 Adds management command `load_meta_icd11_diagnosis` to load ICD11 to database (postgres)
  care/facility/admin.py
  care/facility/management/commands/load_meta_icd11_diagnosis.py
  care/facility/migrations/0337_metaicd11diagnosis.py
  care/facility/models/__init__.py
  care/facility/models/meta_icd11_diagnosis.py
Labels: changes required

#1261 Fix conflicting migrations
  care/facility/migrations/0346_merge_20230419_0952.py
Labels: P1

#1246 Support free flow text for assigned_facility in Shifting form
  care/facility/api/serializers/shifting.py
  care/facility/migrations/0344_shiftingrequest_assigned_facility_external.py
  care/facility/migrations/0348_merge_20230421_1917.py
  care/facility/models/shifting.py
Labels: waiting-for-review

#1265 Add additional fields in shifting form
  care/facility/api/serializers/shifting.py
  care/facility/migrations/0349_auto_20230422_2058.py
  care/facility/migrations/0350_auto_20230422_2114.py
  care/facility/models/shifting.py
Labels: waiting-for-review

#1268 fix: districtadmin can't set shifting patient status as completed
  care/facility/api/serializers/shifting.py
Labels: waiting-for-review, P1

#1223 feat: Add patient and bed count to Facility serializers
  care/facility/api/serializers/facility.py
Labels: waiting-for-review

#1276 Fix issues with Shifting
  care/facility/api/serializers/shifting.py
  care/utils/notification_handler.py
Labels: waiting-for-review

#1262 Add NONE to patient action
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0351_auto_20230424_1227.py
  care/facility/models/patient.py
Labels: waiting-for-review, P1

#1278 Discharge patient on shifting complete
  care/facility/api/serializers/shifting.py
Labels: waiting-for-review

#1280 fix: removed patient_category from the shifting model
  care/facility/api/serializers/shifting.py
  care/facility/migrations/0352_auto_20230428_1539.py
  care/facility/models/shifting.py
Labels: waiting-for-review, P1

#1269 Allow transfer for patients defaults to `true` if `peacetime`, else `false`
  care/facility/api/serializers/patient.py
Labels: waiting-for-review, P1
