Repository ohcnetwork/care, pull requests merged in 2023-08, with the labels that each got.

#1275 Modified bedCreate API View to support bulk creating beds
  care/facility/api/serializers/bed.py
  care/facility/api/viewsets/bed.py
  care/facility/tests/test_bed_create.py
Labels: reviewed

#1484 Added `op_no` and `ip_OR_op` Filters for Patients
  care/facility/api/viewsets/patient.py
  care/facility/tests/test_patient_api.py
Labels: waiting-for-review

#1495 Add weekly working hours field for users
  care/users/api/serializers/user.py
  care/users/migrations/0006_user_weekly_working_hours.py
  care/users/models.py
  care/users/tests/test_api.py
Labels: waiting-for-review

#1501 Add missing migration for dailyround
  care/facility/migrations/0375_alter_dailyround_resp.py
Labels: waiting-for-review

#1510 fix discharge summary progress check
  care/facility/api/viewsets/patient_consultation.py
  care/facility/utils/reports/discharge_summary.py
Labels: reviewed

#1519 Pop `death_datetime` and `death_confirmed_doctor` if discharge reason other than EXPIRED
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0376_auto_20230807_2148.py
  care/facility/tests/test_patient_consultation_api.py
Labels: P1, reviewed

#1517 Removes pre-commit missing migrations check
  .pre-commit-config.yaml
Labels: reviewed

#1515 track abha numbers created by care
  care/abdm/api/viewsets/healthid.py
  care/abdm/migrations/0008_abhanumber_new.py
  care/abdm/models.py
Labels: P1, reviewed

#1503 Optimisation: set `update_fields` for instance delete
  care/utils/models/base.py
Labels: reviewed

#1502 Skip validation if asset warranty date is not changed
  care/facility/api/serializers/asset.py
  care/facility/tests/test_asset_api.py
Labels: reviewed

#1508 Adds utility class validator: `PhoneNumberValidator`
  care/facility/api/viewsets/patient_otp.py
  care/facility/migrations/0376_alter_ambulance_owner_phone_number_and_more.py
  care/facility/models/ambulance.py
  care/facility/models/asset.py
  care/facility/models/base.py
  care/facility/models/facility.py
  care/facility/models/patient.py
  care/facility/models/resources.py
  care/facility/models/shifting.py
  care/facility/tests/test_phone_number_validator.py
  care/users/migrations/0007_alter_user_alt_phone_number_alter_user_phone_number.py
  care/users/models.py
  care/utils/models/validators.py
  care/utils/sms/sendSMS.py
  care/utils/tests/test_phone_number_validator.py
Labels: reviewed

#1506 Add referred facility to discharge serializer
  care/facility/api/serializers/patient_consultation.py
  care/facility/tests/test_patient_consultation_api.py
Labels: waiting-for-review

#1446 Fix issues with HCX
  .github/workflows/deployment-branch.yaml
  care/hcx/utils/fhir.py
  care/hcx/utils/hcx/__init__.py
Labels: waiting-for-review

#1522 Rename prescribed_medication to treatment_plan
  care/abdm/utils/fhir.py
  care/facility/migrations/0379_rename_prescribed_medication_patientconsultation_treatment_plan.py
  care/facility/models/patient_consultation.py
  care/facility/tests/test_patient_consultation_api.py
  care/templates/reports/patient_discharge_summary_pdf.html
  care/utils/tests/test_base.py
  data/dummy/facility.json
Labels: reviewed

#1525 Migration to Rename Skill and Add New Skill
  care/users/migrations/0008_rename_skill_and_add_new_20230817_1937.py
Labels: P1, reviewed

#1544 feat: add list of uploaded files to discharge summary
  care/facility/utils/reports/discharge_summary.py
  care/templates/reports/patient_discharge_summary_pdf.html
Labels: reviewed

#1507 Made doctor role as static attribute
  care/facility/api/serializers/patient.py
  care/facility/api/viewsets/patient.py
  care/facility/migrations/0380_patientnotes_user_type.py
  care/facility/models/patient.py
  care/facility/tests/test_patient_api.py
  care/utils/tests/test_base.py
Labels: reviewed

#1277 feat: Add service request history for asset
  care/facility/api/serializers/asset.py
  care/facility/api/viewsets/asset.py
  care/facility/migrations/0382_assetservice_remove_asset_last_serviced_on_and_more.py
  care/facility/models/asset.py
  care/facility/tests/test_asset_service_history_api.py
  config/api_router.py
Labels: reviewed

#1554 fix: assets in use by consultation filter
  care/facility/api/serializers/bed.py
  care/facility/api/viewsets/asset.py
  care/facility/tests/test_asset_api.py
  care/facility/tests/test_consultation_bed_asset_api.py
Labels: reviewed

#1557 Sorts medicine name exact matches first
  care/facility/api/viewsets/prescription.py
  care/facility/tests/test_medibase_api.py
Labels: waiting-for-review, P1

#1564 Adds filter `administered_date` in Medicine Administrations Viewset
  care/facility/api/viewsets/prescription.py
Labels: waiting-for-review

#1560 Add Hard Limit to Medicines Search
  care/facility/api/viewsets/prescription.py
Labels: waiting-for-review

#1566 Adds `type` filter to Medibase search
  care/facility/api/viewsets/prescription.py
Labels: waiting-for-review
