Repository ohcnetwork/care, pull requests merged in 2024-09, with the labels that each got.

#2161 Convert ABDM into Plug - Part 1/3
  care/abdm/api/serializers/abha.py
  care/abdm/api/serializers/abha_number.py
  care/abdm/api/serializers/abhanumber.py
  care/abdm/api/serializers/consent.py
  care/abdm/api/viewsets/abha.py
  care/abdm/api/viewsets/abha_number.py
  care/abdm/api/viewsets/auth.py
  care/abdm/api/viewsets/consent.py
  care/abdm/api/viewsets/health_information.py
  care/abdm/api/viewsets/healthid.py
  care/abdm/api/viewsets/hip.py
  care/abdm/migrations/0013_abhanumber_patient.py
  care/abdm/models/abha_number.py
  care/abdm/receivers/consultation.py
  care/abdm/service/gateway.py
  care/abdm/service/request.py
  care/abdm/utils/api_call.py
  care/facility/api/serializers/patient.py
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0454_remove_historicalpatientregistration_abha_number_and_more.py
  care/facility/models/patient.py
  config/api_router.py
  data/dummy/facility.json
Labels: ABDM

#2456 Fixed abha linking issue
  care/abdm/api/serializers/healthid.py
  care/abdm/api/viewsets/abha_number.py
  care/abdm/api/viewsets/healthid.py
Labels: reviewed

#2458 Fixed abha linking issue
  care/abdm/api/serializers/healthid.py
  care/abdm/api/viewsets/abha_number.py
  care/abdm/api/viewsets/healthid.py
Labels: reviewed

#2464 Adds fields for social profile: socioeconomic status and domestic healthcare support
  care/facility/api/serializers/patient.py
  care/facility/migrations/0457_patientmetainfo_domestic_healthcare_support_and_more.py
  care/facility/models/patient.py
  care/facility/tests/test_patient_api.py
Labels: P1

#2133 Prescriptions and MAR: Disallow users to perform edits on discharged encounters
  care/facility/api/serializers/prescription.py
  care/facility/api/viewsets/prescription.py
  care/facility/tests/test_medicine_administrations_api.py
  care/facility/tests/test_medicine_api.py
  care/facility/tests/test_prescriptions_api.py
Labels: P2

#2399 HCX Plug
  care/facility/api/serializers/patient.py
  care/facility/management/commands/load_redis_index.py
  care/facility/tasks/redis_index.py
  care/facility/tests/sample_reports/sample2.png
  care/facility/tests/test_pdf_generation.py
  care/facility/utils/reports/discharge_summary.py
  care/hcx/__init__.py
  care/hcx/api/serializers/claim.py
  care/hcx/api/serializers/communication.py
  care/hcx/api/serializers/gateway.py
  care/hcx/api/serializers/policy.py
  care/hcx/api/viewsets/claim.py
  care/hcx/api/viewsets/communication.py
  care/hcx/api/viewsets/gateway.py
  care/hcx/api/viewsets/listener.py
  care/hcx/api/viewsets/policy.py
  care/hcx/apps.py
  care/hcx/migrations/0001_initial_squashed.py
  care/hcx/migrations/0002_alter_claim_id_alter_claim_items_alter_policy_id.py
  care/hcx/migrations/0007_communication.py
  care/hcx/migrations/0008_merge_20230617_1253.py
  care/hcx/migrations/0009_alter_communication_content_alter_communication_id.py
  care/hcx/migrations/__init__.py
  care/hcx/migrations_old/0001_initial.py
  care/hcx/migrations_old/0002_claim.py
  care/hcx/migrations_old/0003_auto_20230217_1901.py
  care/hcx/migrations_old/0004_auto_20230222_2012.py
  care/hcx/migrations_old/0005_auto_20230222_2217.py
  care/hcx/migrations_old/0006_auto_20230323_1208.py
  care/hcx/migrations_old/__init__.py
  care/hcx/models/base.py
  care/hcx/models/claim.py
  care/hcx/models/communication.py
  care/hcx/models/json_schema/claim.py
  care/hcx/models/json_schema/communication.py
  care/hcx/models/policy.py
  care/hcx/static_data/__init__.py
  care/hcx/static_data/pmjy_packages.py
  care/hcx/utils/fhir.py
  care/hcx/utils/hcx/__init__.py
  care/hcx/utils/hcx/operations.py
  care/templates/reports/patient_discharge_summary_pdf_template.typ
  care/utils/queryset/communications.py
  care/utils/tests/test_utils.py
  config/api_router.py
  config/settings/base.py
  config/urls.py
  docker/.local.env
  docker/.prebuilt.env
  plug_config.py
Labels: peer-reviewed

#2473 Allow installing plugs from env
  docker/prod.Dockerfile
  install_plugins.py
  plugs/__init__.py
  plugs/manager.py
  plugs/plug.py
Labels: blocked
