Repository ohcnetwork/care, pull requests merged in 2024-03, with the labels that each got.

#1945 Fix bed assignment validation for admission
  care/facility/api/serializers/daily_round.py
  care/facility/tests/test_patient_consultation_api.py
  care/facility/tests/test_patient_daily_rounds_api.py
  care/utils/tests/test_utils.py
Labels: P1

#1954 Allow empty op number
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0415_auto_20240227_0130.py
  care/facility/migrations/0416_patientconsultation_unique_patient_no_within_facility.py
  care/facility/migrations/0419_alter_patientconsultation_patient_no.py
  care/facility/models/patient_consultation.py
  care/facility/tests/test_patient_consultation_api.py
Labels: P1

#1692 Prescription: Titrated drug dose
  care/facility/api/serializers/patient_consultation.py
  care/facility/api/serializers/prescription.py
  care/facility/api/viewsets/prescription.py
  care/facility/migrations/0415_rename_dosage_prescription_base_dosage_and_more.py
  care/facility/models/prescription.py
  care/facility/tests/test_medicine_api.py
  care/facility/tests/test_prescriptions_api.py
  care/facility/utils/reports/discharge_summary.py
  care/templates/reports/patient_discharge_summary_pdf.html
  data/dummy/facility.json
Labels: waiting-for-review

#1999 fixes issues with patient annotate + distinct not implemented for csv export
  care/facility/api/viewsets/patient.py
Labels: P2

#2009 Fixes discharged patients CSV export
  care/facility/api/viewsets/patient.py
Labels: P2

#2006 Added consent records to patient consultation
  care/facility/api/serializers/file_upload.py
  care/facility/migrations/0423_patientconsultation_consent_records_and_more.py
  care/facility/models/file_upload.py
  care/facility/models/json_schema/consultation.py
  care/facility/models/patient_consultation.py
  care/facility/tests/test_file_upload.py
  care/users/models.py
Labels: do-not-merge, P1
