Repository ohcnetwork/care, pull requests merged in 2024-01, with the labels that each got.

#1807 added error handling for get_hip_id_by_health_id
  care/abdm/api/viewsets/auth.py
  care/abdm/api/viewsets/healthid.py
  care/abdm/api/viewsets/hip.py
  care/abdm/utils/api_call.py
  care/facility/api/serializers/patient_consultation.py
Labels: P1, ABDM

#1737 Enhanced Error Handling in AssetViewSet
  care/facility/api/viewsets/asset.py
Labels: waiting-for-review

#1773 Data Migration to Support New Discharge Reason Field
  care/facility/api/serializers/patient.py
  care/facility/api/serializers/patient_consultation.py
  care/facility/api/serializers/shifting.py
  care/facility/api/viewsets/patient.py
  care/facility/api/viewsets/shifting.py
  care/facility/migrations/0405_auto_20231211_1930.py
  care/facility/models/patient_base.py
  care/facility/tests/test_patient_api.py
  care/facility/tests/test_patient_consultation_api.py
  care/templates/reports/patient_discharge_summary_pdf.html
Labels: waiting-for-review

#1818 Fix patient discharge_reason filter and add it to export
  care/facility/api/viewsets/patient.py
  care/facility/models/patient.py
  care/facility/models/patient_base.py
Labels: P1

#1819 Add nurse user type
  care/facility/api/viewsets/bed.py
  care/facility/api/viewsets/file_upload.py
  care/facility/api/viewsets/hospital_doctor.py
  care/facility/api/viewsets/notification.py
  care/facility/api/viewsets/patient_external_test.py
  care/facility/api/viewsets/patient_sample.py
  care/facility/api/viewsets/shifting.py
  care/facility/migrations/0001_initial_squashed.py
  care/facility/models/asset.py
  care/facility/models/base.py
  care/facility/models/daily_round.py
  care/facility/models/mixins/permissions/asset.py
  care/facility/models/mixins/permissions/base.py
  care/facility/models/mixins/permissions/facility.py
  care/facility/models/mixins/permissions/patient.py
  care/facility/models/patient_consultation.py
  care/facility/models/patient_sample.py
  care/facility/models/resources.py
  care/facility/models/shifting.py
  care/users/api/serializers/user.py
  care/users/api/viewsets/users.py
  care/users/api/viewsets/userskill.py
  care/users/migrations/0012_alter_user_user_type.py
  care/users/migrations/0013_staff_to_nurse.py
  care/users/models.py
  care/utils/notification_handler.py
  care/utils/tests/test_utils.py
  config/authentication.py
  data/dummy/users.json
Labels: P1

#1820 Fix patient discharge_reason filter and add it to export
  care/facility/api/serializers/patient.py
Labels: P1

#1808 Added new routes in prescription
  care/facility/migrations/0405_alter_prescription_route.py
  care/facility/models/prescription.py
Labels: waiting-for-review

#1824 Added whitelist of file types in file upload
  care/facility/api/serializers/file_upload.py
  care/facility/models/file_upload.py
  care/facility/tests/test_file_upload.py
  config/settings/base.py
Labels: P1

#1788 Replace littletable with redis-om(redisearch)
  .dockerignore
  .github/workflows/test-base.yml
  Makefile
  Pipfile
  Pipfile.lock
  care/abdm/utils/fhir.py
  care/facility/api/serializers/consultation_diagnosis.py
  care/facility/api/viewsets/icd.py
  care/facility/api/viewsets/prescription.py
  care/facility/management/commands/load_redis_index.py
  care/facility/models/patient.py
  care/facility/static_data/icd11.py
  care/facility/static_data/medibase.py
  care/facility/tasks/__init__.py
  care/facility/tasks/redis_index.py
  care/facility/tests/test_icd11_search.py
  care/facility/utils/reports/discharge_summary.py
  care/hcx/api/viewsets/gateway.py
  care/hcx/static_data/pmjy_packages.py
  care/utils/static_data/__init__.py
  care/utils/static_data/helpers.py
  care/utils/static_data/models/__init__.py
  care/utils/static_data/models/base.py
  config/exception_handler.py
  config/settings/base.py
  config/urls.py
  config/views.py
  config/wsgi.py
  docker-compose.local.yaml
  docker-compose.pre-built.yaml
  docker-compose.yaml
  docker/dev.Dockerfile
  docker/prod.Dockerfile
  scripts/celery-dev.sh
  scripts/celery_beat-ecs.sh
  scripts/celery_beat.sh
  scripts/celery_worker-ecs.sh
  scripts/celery_worker.sh
  scripts/healthcheck.sh
  scripts/start-dev.sh
  scripts/start-ecs.sh
  scripts/start.sh
Labels: waiting-for-review, P1

#1830 Adds support for filtering patients by diagnoses
  care/facility/api/viewsets/icd.py
  care/facility/api/viewsets/patient.py
  care/facility/tests/test_icd11_api.py
  care/facility/tests/test_patient_api.py
  care/utils/tests/test_utils.py
Labels: waiting-for-review, P2

#1852 Load all icd11 records to redis; search filter by `has_code`
  care/facility/api/viewsets/icd.py
  care/facility/static_data/icd11.py
Labels: P1
