Repository ohcnetwork/care, pull requests merged in 2024-06, with the labels that each got.

#2232 update default patient list to show recently_modified first after no_consultation_filed
  care/facility/api/viewsets/patient.py
Labels: P0

#2147 Fix op number constraint for readmitted patients
  care/facility/api/serializers/patient_consultation.py
  care/facility/migrations/0442_remove_patientconsultation_unique_patient_no_within_facility.py
  care/facility/models/patient_consultation.py
  care/facility/tests/test_patient_consultation_api.py
Labels: P1

#2243 Make sentry event level configurable and use error by default
  config/settings/deployment.py
Labels: P0

#2244 Add health check for celery queue length
  config/settings/base.py
Labels: P0

#2242 Add endpoint to get version info
  config/settings/base.py
  config/settings/deployment.py
  config/urls.py
  config/views.py
Labels: P0

#2209 Add Consent Model
  care/facility/admin.py
  care/facility/api/serializers/file_upload.py
  care/facility/api/serializers/patient_consultation.py
  care/facility/api/viewsets/file_upload.py
  care/facility/api/viewsets/patient_consultation.py
  care/facility/migrations/0443_remove_patientconsultation_consent_records_and_more.py
  care/facility/models/file_upload.py
  care/facility/models/patient_consultation.py
  care/facility/tests/test_file_upload.py
  care/facility/tests/test_patient_consents_api.py
  care/utils/tests/test_utils.py
  config/api_router.py
Labels: P0

#2206 Allow Nurses to clear their home facility
  care/facility/tests/test_unlink_district_admins.py
  care/users/api/viewsets/users.py
Labels: P2

#2114 Prevent destination facility from marking shift as complete
  care/facility/api/serializers/shifting.py
Labels: P2
