Repository ohcnetwork/care, pull requests merged in 2024-04, with the labels that each got.

#2012 Map nurse logins to facility.
  data/dummy/facility.json
Labels: reviewed

#1966 Dropped `age` column from patient registration and annotated age in patient viewset
  care/facility/admin.py
  care/facility/api/serializers/patient.py
  care/facility/api/viewsets/patient.py
  care/facility/migrations/0424_remove_patientregistration_age_and_add_patientregistration_death_datetime.py
  care/facility/models/patient.py
  care/facility/models/patient_consultation.py
  care/facility/models/patient_icmr.py
  care/utils/tests/test_utils.py
  data/dummy/facility.json
Labels: P2

#2053 Update discharge summary to reflect age and year of birth
  care/facility/models/patient.py
  care/templates/reports/patient_discharge_summary_pdf.html
Labels: P0

#2036 Add Plugin Support
  .gitignore
  Pipfile
  Pipfile.lock
  care/facility/migrations/0426_alter_fileupload_file_type.py
  care/facility/models/file_upload.py
  config/settings/base.py
  config/urls.py
  docker/dev.Dockerfile
  docker/prod.Dockerfile
  docs/conf.py
  docs/index.rst
  docs/pluggable-apps/configuration.md
  install_plugins.py
  plug_config.py
  plugs/manager.py
  plugs/plug.py
  setup.py
Labels: blocked

#2000 Make care single source of truth for asset config on middleware
  Pipfile
  Pipfile.lock
  care/facility/api/serializers/asset.py
  care/facility/api/serializers/patient_consultation.py
  care/facility/api/viewsets/asset.py
  care/facility/api/viewsets/mixins/access.py
  care/facility/api/viewsets/open_id.py
  care/facility/api/viewsets/patient.py
  care/facility/api/viewsets/patient_consultation.py
  care/facility/apps.py
  care/facility/migrations/0427_dailyround_is_parsed_by_ocr.py
  care/facility/models/daily_round.py
  care/facility/signals/__init__.py
  care/facility/signals/asset_updates.py
  care/facility/tasks/push_asset_config.py
  care/facility/tests/test_middleware_auth.py
  care/utils/jwks/token_generator.py
  config/api_router.py
  config/authentication.py
  config/health_views.py
  config/urls.py
Labels: peer-reviewed, P0

#2084 Handle missing instance.resolved_middleware in asset_updates
  care/facility/signals/asset_updates.py
Labels: P1

#2086 fix patient sorting filters
  care/facility/api/viewsets/patient.py
Labels: P1

#2099 fix query bugs while resolving asset hostname
  care/facility/api/serializers/asset.py
  care/facility/api/viewsets/asset.py
  care/facility/tests/test_asset_api.py
  care/facility/tests/test_middleware_config.py
  care/utils/tests/test_utils.py
Labels: bug, P1

#2112 Remove defining `date_of_birth` and `year_of_birth` serializer fields
  care/facility/api/serializers/patient.py
  care/facility/models/tests/test_patient.py
Labels: P0
