Repository ohcnetwork/care, pull requests merged in 2024-05, with the labels that each got.

#2101 Annotate CSV export fields with patient age for sample test and shifting
  care/facility/api/viewsets/patient_sample.py
  care/facility/api/viewsets/shifting.py
  care/facility/models/patient.py
  care/facility/models/patient_sample.py
  care/facility/models/shifting.py
Labels: P1

#2118 Serialized gender into UserAssignedSerializer
  care/users/api/serializers/user.py
Labels: P1

#2137 Adds support for doctors and nurses discussions threads in Discussion Notes
  care/facility/api/serializers/patient.py
  care/facility/api/viewsets/patient.py
  care/facility/migrations/0431_patientnotes_thread.py
  care/facility/models/patient.py
  care/facility/tests/test_patient_api.py
Labels: P1

#1829 ABDM M3
  .gitignore
  aws/backend.json
  aws/celery.json
  care/abdm/api/serializers/consent.py
  care/abdm/api/viewsets/auth.py
  care/abdm/api/viewsets/consent.py
  care/abdm/api/viewsets/health_information.py
  care/abdm/api/viewsets/patients.py
  care/abdm/migrations/0011_alter_abhanumber_abha_number_and_more.py
  care/abdm/migrations/0012_consentrequest_status.py
  care/abdm/models/__init__.py
  care/abdm/models/abha_number.py
  care/abdm/models/base.py
  care/abdm/models/consent.py
  care/abdm/models/health_facility.py
  care/abdm/models/json_schema.py
  care/abdm/models/permissions/health_facility.py
  care/abdm/service/gateway.py
  care/abdm/service/request.py
  care/abdm/urls.py
  care/abdm/utils/api_call.py
  care/abdm/utils/cipher.py
  care/facility/migrations/0432_alter_fileupload_file_type.py
  care/facility/models/file_upload.py
  care/facility/models/icd11_diagnosis.py
  config/api_router.py
  config/settings/base.py
Labels: peer-reviewed, ABDM

#2174 make rate limit messages user friendly
  care/abdm/api/viewsets/consent.py
  care/abdm/api/viewsets/health_information.py
  care/abdm/api/viewsets/healthid.py
  care/abdm/api/viewsets/patients.py
  config/ratelimit.py
Labels: ABDM, P0

#2187 Renamed patient category labels
  care/facility/migrations/0438_alter_dailyround_patient_category_and_more.py
  care/facility/models/patient_base.py
Labels: P0

#2176 Removed Discharge Filters, reused patient filters
  care/facility/api/viewsets/patient.py
Labels: P0

#2186 Symptoms table
  care/facility/api/serializers/daily_round.py
  care/facility/api/serializers/encounter_symptom.py
  care/facility/api/serializers/patient_consultation.py
  care/facility/api/serializers/patient_icmr.py
  care/facility/api/viewsets/encounter_symptom.py
  care/facility/api/viewsets/patient.py
  care/facility/management/commands/load_event_types.py
  care/facility/migrations/0439_encounter_symptoms.py
  care/facility/models/__init__.py
  care/facility/models/daily_round.py
  care/facility/models/encounter_symptom.py
  care/facility/models/patient_consultation.py
  care/facility/models/patient_icmr.py
  care/facility/tests/test_encounter_symptom_api.py
  care/facility/tests/test_patient_consultation_api.py
  care/facility/utils/reports/discharge_summary.py
  care/templates/reports/patient_discharge_summary_pdf.html
  care/utils/tests/test_utils.py
  config/api_router.py
  data/dummy/facility.json
Labels: P1

#2201 Adds support to specify and filter ration card category of a patient
  care/facility/api/viewsets/patient.py
  care/facility/migrations/0439_historicalpatientregistration_ration_card_category_and_more.py
  care/facility/models/patient.py
  care/templates/reports/patient_discharge_summary_pdf.html
  care/utils/tests/test_utils.py
Labels: P1

#2193 fix redis tokenization for icd11 ids
  Pipfile
  Pipfile.lock
  care/facility/api/viewsets/icd.py
  care/facility/static_data/icd11.py
  care/facility/tests/test_icd11_api.py
  care/utils/static_data/helpers.py
Labels: P1

#2200 Fixes state and district admin not able to see users of same user type level
  care/users/api/viewsets/users.py
  care/users/tests/test_facility_user_create.py
Labels: bug, P2
